import React from 'react';

const PrivacyPolicyPage: React.FC = () => {
    return (
        <div className="glass-card p-6 md:p-8 rounded-2xl animate-fade-in">
            <div className="max-w-4xl mx-auto text-gray-300 prose prose-invert prose-p:text-gray-300 prose-h1:text-white prose-h2:text-brand-primary prose-h3:text-white prose-li:text-gray-300 legal-text">
                <h1 className="text-4xl font-bold text-white mb-6 text-center">Privacy Policy</h1>
                <p><strong>Last Updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

                <p>
                    Welcome to <strong>QuickLink</strong> ("Company", "We", "Us", "Our"). We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website and use our URL shortening and QR code generation services (collectively, the "Service"). <strong>Please read this privacy policy carefully.</strong> If you do not agree with the terms of this privacy policy, please do not access the service.
                </p>

                <h2>1. Interpretation and Definitions</h2>
                <h3>Interpretation</h3>
                <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                <h3>Definitions</h3>
                <ul>
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to QuickLink.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the QuickLink website and all its functionalities.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>You</strong> means the individual access or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
                
                <h2>2. Collecting and Using Your Personal Data</h2>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                <ul>
                    <li>Email address (when creating an account)</li>
                    <li>First name and last name (when creating an account)</li>
                    <li>Payment information (processed by our third-party payment provider, Razorpay. <strong>We do not store your full card details</strong>).</li>
                </ul>

                <h4>Usage Data</h4>
                <p><strong>Usage Data</strong> is collected automatically when using the Service. Usage Data may include information such as Your device's Internet Protocol (IP) address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                
                <h4>Tracking Technologies and Cookies</h4>
                <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. We use both Session and Persistent Cookies for the purposes set out below:</p>
                 <ul>
                    <li><strong>Necessary / Essential Cookies:</strong> These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</li>
                    <li><strong>Functionality Cookies:</strong> These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
                </ul>

                <h3>Use of Your Personal Data</h3>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul>
                    <li><strong>To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
                    <li><strong>To manage Your Account:</strong> To manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
                    <li><strong>For the performance of a contract:</strong> For services you have purchased, such as a subscription plan.</li>
                    <li><strong>To contact You:</strong> To contact You by email regarding updates, your subscription status, or informative communications related to the functionalities.</li>
                     <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                </ul>

                <h2>3. Disclosure of Your Personal Data</h2>
                <p><strong>We do not sell, trade, or otherwise transfer to outside parties your Personally Identifiable Information</strong> unless we provide users with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or serving our users, so long as those parties agree to keep this information confidential. We may also release information when its release is appropriate to comply with the law, enforce our site policies, or protect ours or others' rights, property or safety.</p>

                <h2>4. Retention and Security of Your Personal Data</h2>
                 <p>We will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to <strong>comply with our legal obligations</strong>, resolve disputes, and enforce our legal agreements and policies.</p>
                <p>The security of Your Personal Data is important to Us, but remember that <strong>no method of transmission over the Internet, or method of electronic storage is 100% secure</strong>. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
                
                <h2>5. Children's Privacy</h2>
                <p>Our Service does not address anyone under the age of 13. <strong>We do not knowingly collect personally identifiable information from anyone under the age of 13.</strong> If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>

                <h2>6. Changes to this Privacy Policy</h2>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. <strong>You are advised to review this Privacy Policy periodically for any changes.</strong> Changes to this Privacy Policy are effective when they are posted on this page.</p>

                <h2>7. Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, You can contact us by visiting the social media and contact links provided on this website.</p>
            </div>
        </div>
    );
};

export default PrivacyPolicyPage;