// ===================================================================================
//   🏷️ PROJECT: QuickLink - Fast & Secure URL Shortener, QR Generator & API
//   👨‍💻 AUTHOR: Deep Dey (Ceo,Dev,Founder)
//   🛡️ Helper: Google Gemini & ChatGPT
//   🌐 WEBSITE: https://qlynk.vercel.app
//   📅 CREATED: 2025
//   🧠 DESCRIPTION:
//       QuickLink is a secure, high-performance web application designed for 
//       shortening URLs, generating QR codes, and providing developers with 
//       easy-to-integrate API services. Built with simplicity, reliability, 
//       and speed in mind by Deep Dey.
//
//   ⚙️ TECHNOLOGY STACK:
//       - HTML, CSS, TypeScript
//       - Node.js / Express (Backend)
//       - Vercel (Deployment)
//       - JSON API Integration
//
//   📩 CONTACT:
//       ✉️ Email: thedeeparise@gmail.com
//       🔗 GitHub: https://github.com/deepdeyiitgn/QuickLink
//       🧾 License: All Rights Reserved © 2025 Deep Dey
//       💬 Instagram: https://www.instagram.com/deepdey.official/
//
//   ⚠️ LEGAL NOTICE:
//       This source code is the intellectual property of Deep Dey. 
//       Any unauthorized copying, modification, distribution, or use of 
//       this project in whole or in part without written permission is 
//       strictly prohibited and may result in legal action.
//
// ===================================================================================
import React from 'react';
import { Helmet } from 'react-helmet';
// FIX: Corrected import from "react-router-dom" to resolve module not found errors by changing single quotes to double quotes.
import { Link } from "react-router-dom";
import AdComponent from '../AdComponent';

const SecurityFeaturePage: React.FC = () => {
    return (
        <>
            <Helmet>
                <title>2FA Security | QuickLink Features</title>
                <meta name="description" content="Protect your QuickLink account with Two-Factor Authentication (2FA). Learn how to set up an extra layer of security using your favorite authenticator app." />
            </Helmet>

            <div className="space-y-12">
                <div className="text-center">
                    <h1 className="text-5xl font-bold text-white mb-4 animate-aurora">2FA Security</h1>
                    <p className="text-lg text-gray-400 max-w-2xl mx-auto">
                        Protect Your Account with an Extra Layer of Security.
                    </p>
                    <Link to="/features" className="text-brand-primary hover:underline mt-4 inline-block">&larr; Back to All Features</Link>
                </div>

                <div className="grid md:grid-cols-2 gap-8 items-center">
                    <div className="glass-card p-8 rounded-2xl">
                        <h2 className="text-3xl font-bold text-brand-primary mb-4">What is 2-Factor Authentication?</h2>
                        <p className="text-gray-300">
                           Two-Factor Authentication (2FA) adds a critical second layer of security to your account. When you log in, you'll need both your password and a time-sensitive, 6-digit code generated by an authenticator app on your phone (like Google Authenticator, Authy, or Microsoft Authenticator).
                        </p>
                    </div>
                    <div className="flex justify-center">
                         <svg width="250" height="250" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" stroke="#846cff" strokeWidth="1.5"/>
                            <path d="M9 10.5C9 9.11929 10.1193 8 11.5 8C12.8807 8 14 9.11929 14 10.5V12.5C14 13.8807 12.8807 15 11.5 15C10.1193 15 9 13.8807 9 12.5V10.5Z" stroke="#00e5ff" strokeWidth="1.5"/>
                            <path d="M11.5 15V17" stroke="#00e5ff" strokeWidth="1.5" strokeLinecap="round"/>
                            <path d="M11.5 7.5V9.5" stroke="#00e5ff" strokeWidth="1.5" strokeLinecap="round"/>
                        </svg>
                    </div>
                </div>

                <div className="max-w-4xl mx-auto my-8">
                     <AdComponent type="display" />
                </div>
                
                 <div className="glass-card p-8 rounded-2xl">
                    <h2 className="text-3xl font-bold text-brand-secondary mb-6 text-center">Why It's Essential</h2>
                     <p className="text-gray-300 text-center max-w-2xl mx-auto mb-6">
                        Even if a malicious actor steals your password, they won't be able to access your account without the physical possession of your phone. This simple step provides a massive boost to your digital security, protecting your links, data, and subscriptions from unauthorized access.
                    </p>
                </div>

                <div className="max-w-4xl mx-auto my-8">
                     <AdComponent type="in-feed" />
                </div>

                <div className="grid md:grid-cols-2 gap-8 items-center">
                     <div className="glass-card p-8 rounded-2xl md:order-2">
                        <h2 className="text-3xl font-bold text-brand-primary mb-4">Simple & Secure Setup</h2>
                         <ul className="space-y-3 text-gray-300 list-disc list-inside">
                            <li><strong>Verify Identity:</strong> Start by entering your current password to confirm it's you.</li>
                            <li><strong>Scan the QR Code:</strong> Use your authenticator app to scan the unique QR code we generate for your account.</li>
                            <li><strong>Confirm & Activate:</strong> Enter the 6-digit code from your app to finalize the setup. That's it!</li>
                            <li><strong>Admin Recovery:</strong> If you ever lose access to your authenticator app, our support team can securely disable 2FA for your account after verifying your identity.</li>
                        </ul>
                    </div>
                     <div className="flex justify-center md:order-1">
                        <svg width="250" height="250" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M9 12.75L11.25 15L15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" stroke="#00e5ff" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                    </div>
                </div>

                <div className="text-center">
                    <Link to="/dashboard" className="inline-block px-10 py-4 bg-brand-secondary text-white text-lg font-semibold rounded-lg hover:bg-brand-secondary/80 transition-all transform hover:scale-105 shadow-[0_0_20px_#846cff]">
                        Go to Dashboard to Enable 2FA
                    </Link>
                </div>
            </div>
        </>
    );
};

export default SecurityFeaturePage;